# Generated by Django 5.0 on 2023-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
            ],
        ),
    ]
